service: authorization-service
frameworkVersion: "2"

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

  environment:
    username: kabolov
    password: ${env:kabolov}

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
